// Generated by gencpp from file hdl_global_localization/QueryGlobalLocalization.msg
// DO NOT EDIT!


#ifndef HDL_GLOBAL_LOCALIZATION_MESSAGE_QUERYGLOBALLOCALIZATION_H
#define HDL_GLOBAL_LOCALIZATION_MESSAGE_QUERYGLOBALLOCALIZATION_H

#include <ros/service_traits.h>


#include <hdl_global_localization/QueryGlobalLocalizationRequest.h>
#include <hdl_global_localization/QueryGlobalLocalizationResponse.h>


namespace hdl_global_localization
{

struct QueryGlobalLocalization
{

typedef QueryGlobalLocalizationRequest Request;
typedef QueryGlobalLocalizationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryGlobalLocalization
} // namespace hdl_global_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdl_global_localization::QueryGlobalLocalization > {
  static const char* value()
  {
    return "2e563a5d7af1f98cbac55cf8c1e0a1ba";
  }

  static const char* value(const ::hdl_global_localization::QueryGlobalLocalization&) { return value(); }
};

template<>
struct DataType< ::hdl_global_localization::QueryGlobalLocalization > {
  static const char* value()
  {
    return "hdl_global_localization/QueryGlobalLocalization";
  }

  static const char* value(const ::hdl_global_localization::QueryGlobalLocalization&) { return value(); }
};


// service_traits::MD5Sum< ::hdl_global_localization::QueryGlobalLocalizationRequest> should match
// service_traits::MD5Sum< ::hdl_global_localization::QueryGlobalLocalization >
template<>
struct MD5Sum< ::hdl_global_localization::QueryGlobalLocalizationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdl_global_localization::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::hdl_global_localization::QueryGlobalLocalizationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdl_global_localization::QueryGlobalLocalizationRequest> should match
// service_traits::DataType< ::hdl_global_localization::QueryGlobalLocalization >
template<>
struct DataType< ::hdl_global_localization::QueryGlobalLocalizationRequest>
{
  static const char* value()
  {
    return DataType< ::hdl_global_localization::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::hdl_global_localization::QueryGlobalLocalizationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdl_global_localization::QueryGlobalLocalizationResponse> should match
// service_traits::MD5Sum< ::hdl_global_localization::QueryGlobalLocalization >
template<>
struct MD5Sum< ::hdl_global_localization::QueryGlobalLocalizationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdl_global_localization::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::hdl_global_localization::QueryGlobalLocalizationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdl_global_localization::QueryGlobalLocalizationResponse> should match
// service_traits::DataType< ::hdl_global_localization::QueryGlobalLocalization >
template<>
struct DataType< ::hdl_global_localization::QueryGlobalLocalizationResponse>
{
  static const char* value()
  {
    return DataType< ::hdl_global_localization::QueryGlobalLocalization >::value();
  }
  static const char* value(const ::hdl_global_localization::QueryGlobalLocalizationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDL_GLOBAL_LOCALIZATION_MESSAGE_QUERYGLOBALLOCALIZATION_H
