// Generated by gencpp from file hdl_global_localization/SetGlobalMap.msg
// DO NOT EDIT!


#ifndef HDL_GLOBAL_LOCALIZATION_MESSAGE_SETGLOBALMAP_H
#define HDL_GLOBAL_LOCALIZATION_MESSAGE_SETGLOBALMAP_H

#include <ros/service_traits.h>


#include <hdl_global_localization/SetGlobalMapRequest.h>
#include <hdl_global_localization/SetGlobalMapResponse.h>


namespace hdl_global_localization
{

struct SetGlobalMap
{

typedef SetGlobalMapRequest Request;
typedef SetGlobalMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGlobalMap
} // namespace hdl_global_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdl_global_localization::SetGlobalMap > {
  static const char* value()
  {
    return "5ed403eb1abbaa077410b645f248da4e";
  }

  static const char* value(const ::hdl_global_localization::SetGlobalMap&) { return value(); }
};

template<>
struct DataType< ::hdl_global_localization::SetGlobalMap > {
  static const char* value()
  {
    return "hdl_global_localization/SetGlobalMap";
  }

  static const char* value(const ::hdl_global_localization::SetGlobalMap&) { return value(); }
};


// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalMapRequest> should match
// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalMap >
template<>
struct MD5Sum< ::hdl_global_localization::SetGlobalMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdl_global_localization::SetGlobalMap >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdl_global_localization::SetGlobalMapRequest> should match
// service_traits::DataType< ::hdl_global_localization::SetGlobalMap >
template<>
struct DataType< ::hdl_global_localization::SetGlobalMapRequest>
{
  static const char* value()
  {
    return DataType< ::hdl_global_localization::SetGlobalMap >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalMapResponse> should match
// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalMap >
template<>
struct MD5Sum< ::hdl_global_localization::SetGlobalMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdl_global_localization::SetGlobalMap >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdl_global_localization::SetGlobalMapResponse> should match
// service_traits::DataType< ::hdl_global_localization::SetGlobalMap >
template<>
struct DataType< ::hdl_global_localization::SetGlobalMapResponse>
{
  static const char* value()
  {
    return DataType< ::hdl_global_localization::SetGlobalMap >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDL_GLOBAL_LOCALIZATION_MESSAGE_SETGLOBALMAP_H
