// Generated by gencpp from file hdl_global_localization/SetGlobalLocalizationEngine.msg
// DO NOT EDIT!


#ifndef HDL_GLOBAL_LOCALIZATION_MESSAGE_SETGLOBALLOCALIZATIONENGINE_H
#define HDL_GLOBAL_LOCALIZATION_MESSAGE_SETGLOBALLOCALIZATIONENGINE_H

#include <ros/service_traits.h>


#include <hdl_global_localization/SetGlobalLocalizationEngineRequest.h>
#include <hdl_global_localization/SetGlobalLocalizationEngineResponse.h>


namespace hdl_global_localization
{

struct SetGlobalLocalizationEngine
{

typedef SetGlobalLocalizationEngineRequest Request;
typedef SetGlobalLocalizationEngineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGlobalLocalizationEngine
} // namespace hdl_global_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngine > {
  static const char* value()
  {
    return "f71639c3aeb058fa00da5a20981c23c9";
  }

  static const char* value(const ::hdl_global_localization::SetGlobalLocalizationEngine&) { return value(); }
};

template<>
struct DataType< ::hdl_global_localization::SetGlobalLocalizationEngine > {
  static const char* value()
  {
    return "hdl_global_localization/SetGlobalLocalizationEngine";
  }

  static const char* value(const ::hdl_global_localization::SetGlobalLocalizationEngine&) { return value(); }
};


// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngineRequest> should match
// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngine >
template<>
struct MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalLocalizationEngineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdl_global_localization::SetGlobalLocalizationEngineRequest> should match
// service_traits::DataType< ::hdl_global_localization::SetGlobalLocalizationEngine >
template<>
struct DataType< ::hdl_global_localization::SetGlobalLocalizationEngineRequest>
{
  static const char* value()
  {
    return DataType< ::hdl_global_localization::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalLocalizationEngineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngineResponse> should match
// service_traits::MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngine >
template<>
struct MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hdl_global_localization::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalLocalizationEngineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hdl_global_localization::SetGlobalLocalizationEngineResponse> should match
// service_traits::DataType< ::hdl_global_localization::SetGlobalLocalizationEngine >
template<>
struct DataType< ::hdl_global_localization::SetGlobalLocalizationEngineResponse>
{
  static const char* value()
  {
    return DataType< ::hdl_global_localization::SetGlobalLocalizationEngine >::value();
  }
  static const char* value(const ::hdl_global_localization::SetGlobalLocalizationEngineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HDL_GLOBAL_LOCALIZATION_MESSAGE_SETGLOBALLOCALIZATIONENGINE_H
