(cl:defpackage hdl_global_localization-srv
  (:use )
  (:export
   "QUERYGLOBALLOCALIZATION"
   "<QUERYGLOBALLOCALIZATION-REQUEST>"
   "QUERYGLOBALLOCALIZATION-REQUEST"
   "<QUERYGLOBALLOCALIZATION-RESPONSE>"
   "QUERYGLOBALLOCALIZATION-RESPONSE"
   "SETGLOBALLOCALIZATIONENGINE"
   "<SETGLOBALLOCALIZATIONENGINE-REQUEST>"
   "SETGLOBALLOCALIZATIONENGINE-REQUEST"
   "<SETGLOBALLOCALIZATIONENGINE-RESPONSE>"
   "SETGLOBALLOCALIZATIONENGINE-RESPONSE"
   "SETGLOBALMAP"
   "<SETGLOBALMAP-REQUEST>"
   "SETGLOBALMAP-REQUEST"
   "<SETGLOBALMAP-RESPONSE>"
   "SETGLOBALMAP-RESPONSE"
  ))

